### ISSUE TITLE
Provide a default source code vulnerability scanner for Appsody during Git code push

### ISSUE THREAD

**Issue by jtmulvey** [kabanero-io/kabanero-security#12]
We need to provide a default source code vulnerability scanner for Kabanero/Appsody.  This needs to be one that is derived from an open source project.   This feature ensures we have the proper plug-point for this and that the results can be provided back to Appsody to be passed back to developers.

**Comment by teddyjtorres** [comment]
A sample scanner with readme was added to https://github.com/kabanero-io/kabanero-security/tree/master/pipelines/samples. Look into integrating into the sample pipeline using https://github.com/kabanero-io/kabanero-pipelines/issues/4 . The default oscap-docker command is affected by https://github.com/OpenSCAP/openscap/issues/1318 if base image OS is not supported.

**Comment by teddyjtorres** [comment]
Please disregard my comment, it was meant for issue #13
