### ISSUE TITLE
Provide a default container image scanner to be run in Appsody pipeline

### ISSUE THREAD

**Issue by jtmulvey** [kabanero-io/kabanero-security#13]
Need to ensure we have a plugpoint in the Tekton pipeline to plug in a container vulnerability scanner. Results of the scan need to be logged and the build abandoned when the results are severe. The results need to be provided by in the build logs.

**Comment by teddyjtorres** [comment]
A sample scanner with readme was added to https://github.com/kabanero-io/kabanero-security/tree/master/pipelines/samples. Look into integrating into the sample pipeline using kabanero-io/kabanero-pipelines#4 . The default oscap-docker command is affected by OpenSCAP/openscap#1318 if base image OS is not supported.

**Comment by jtmulvey** [comment]
Reset the milestone on this to Oct 4. The sample needs to be converted to a default impl using the open source OpenSCAP.

**Comment by marikaj123** [comment]
Scanning was delivered. A follow-up issue will be opened for the next release.
