### ISSUE TITLE
logout doesn't invalidate JWT

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-security#18]
logout doesn't invalidate JWT

I'm able to invoke role protected endpoints successfully after logout using the current JWT

**Comment by brutif** [comment]
I thought we had this fixed with recent builds.  @davco01a could you check and see if it's still there?

**Comment by davco01a** [comment]
still a problem

**Comment by chunlongliang-ibm** [comment]
The JWT is currently tracked in memory. Do you know if pod is restarted between logout and login?

**Comment by davco01a** [comment]
it is not, but we cannot rely on the pod getting restarted to invalidate the JWT

**Comment by brutif** [comment]
As the old famous saying goes, "works on my machine".  So let's check a few things when you have time.  
1) Does your war file contain the class KabSecFilter?
2) Is your endpoint really secured, can you access it directly without logging in?
The test I did which worked was - 
login
access kabasec/securedping, confirm positive response
logout
access kabasec/securedping, confirm get {"message":"401: The supplied JWT was previously logged out."}
I can send the curl scripts if that helps

**Comment by brutif** [comment]
There was an error in the post request, it's working now

**Comment by davco01a** [comment]
working now
