### ISSUE TITLE
Provide container-based security for scanning containers.

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-security#2]
Provide plug points for vulnerability scans of Kabanero Collections containers.  Need to be able to plug in various providers for this service. There are several places where this is needed.
1) during build of kabanero.io collections images
2) during creation of custom collections by Kabanero admins - for local docker registries
3) during creation of application container images in the CI/CD pipeline

**Comment by jtmulvey** [comment]
Now prototyping use of Clair for this:  https://coreos.com/clair/docs/latest/

**Comment by teddyjtorres** [comment]
A sample scanner with readme was added to https://github.com/kabanero-io/kabanero-security/tree/master/pipelines/samples. Look into integrating into the sample pipeline using https://github.com/kabanero-io/kabanero-pipelines/issues/4 . The default oscap-docker command is affected by https://github.com/OpenSCAP/openscap/issues/1318 if base image OS is not supported.

**Comment by teddyjtorres** [comment]
Updated the scanner in https://github.com/kabanero-io/kabanero-security/pull/32 removing docker dependencies and it no longer requires the docker socket.

**Comment by marikaj123** [comment]
Work is complete
