### ISSUE TITLE
IAM support: Enable Keycloak/RH-SSO for Open Shift for applications use

### ISSUE THREAD

**Issue by jtmulvey** [kabanero-io/kabanero-security#24]
We need to provide a simple way for customers using Kabanero to enable use of Keycloak/RH-SSO for their application purposes.  This should provide a simple out of the box IAM and SSO server for application purposes.

**Comment by marikaj123** [comment]
According to Jim, the feature work is still on track to complete for Kabanero v.0.6.0.

**Comment by marikaj123** [comment]
According to Chunlong, this issue is part of jarek's team. No work will be included in Kabanero. Therefore, it can be closed.

**Comment by marikaj123** [comment]
May need a blog.

**Comment by brutif** [comment]
initial docs are at: https://github.com/kabanero-io/docs/pull/269

**Comment by marikaj123** [comment]
@mtamboli and @brutif - Added the doc,#269, as a child PR to this Epic.
