### ISSUE TITLE
Provide container-based security for signing containers PHASE 1

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-security#3]
Provide plug points for signing Kabanero Collections containers.  Need to be able to plug in various providers for this service.  There are several places where this is needed.  
1) during build of kabanero.io collections images
2) during creation of custom collections by Kabanero admins - for local docker registries
3) during creation of application container images in the CI/CD pipeline

**Comment by marikaj123** [comment]
Security team will try to contain the work in v0.3.0.

**Comment by marikaj123** [comment]
Will ship a doc with sample in release 0.3.0.  In next release will be part of the default pipeline.

**Comment by stephenkinder** [comment]
@jtmulvey does this issue include the validation that containers being used by kabanero are correctly signed, or does that need to be a different epic?

**Comment by jtmulvey** [comment]
This feature is for the signing sample support - PHASE 1 for signing.

**Comment by marikaj123** [comment]
Sample is loaded in the security repo. Teddy, please closed when you can.

**Comment by teddyjtorres** [comment]
The sample is for scenario 3, "during creation of application container images in the CI/CD pipeline".

**Comment by marikaj123** [comment]
@toshiyamamoto - Please update the Readme and close the Epic soon after.  Need to be comeplet during this week, please.

**Comment by toshiyamamoto** [comment]
@marikaj123 sure. I'll do so ASAP.

**Comment by toshiyamamoto** [comment]
The seurity readme was updated to point to the image signing sample. All planned tasks have been completed.
