### ISSUE TITLE
Harden security in Kabanero CLI Liberty server instance

### ISSUE THREAD

**Issue by jtmulvey** [kabanero-io/kabanero-security#31]
We need to set the following options in the server.xml of the Kabanero CLI Liberty instance to ensure we have the most secure configuration possible enabled.  As doc'd in our Liberty for production hardening guide: https://ibm.box.com/s/blluvgl8pl8hmaiapk68byalavew64ip
1) make sure the Liberty server's identity does NOT own the server's configuration and instead only has READ access to it - use the WLP_OUTPUT_DIR environment variable to point to the logs  -the server ID only owns the directory/file this points to
2) make sure any sensitive info in the server.xml is AES encrypted
3) ensure the featureManager list only includes the web container (servlet feature)
4) disable all non-SSL ports : httpPort=”-1" in the httpEndpoint stanza
5) use feature transportSecurity-1.0 instead of ssl-1.0
6) add webAppSecurity ssoRequiresSSL=’true’ to server.xml
7) add webAppSecurity httpOnlyCookies=’true’ to server.xml
8) add httpSession cookieHttpOnly=’true’ to server.xml
9) disable dynamic updates : the dropins folder : applicationMonitor updateTrigger="mbean" dropinsEnabled="false" and config dyn. updates config updateTrigger="mbean" in server.xml
10) disable default welcome page : httpDispatcher enableWelcomePage="false" in server.xml
11) set httpOptions removeServerHeader="true" in server.xml
12) set webContainer disableXPoweredBy="true" in server.xml
13) if using the IBM Java SE 8 JDK, set jvm.options-Dcom.ibm.jsse2.sp800-131=strict-Djdk.tls.client.protocols=TLSv1.2-Dhttps.protocols=TLSv1.2
14) disable HTTP session overflow:  httpSession allowOverflow="false" maxInMemorySessionCount="1000" alwaysEncodeUrl="true" cookieSecure="true" cookieHttpOnly=true
Last make sure the servlet has all HTTP methods covered and return 403 (forbidden) (TRACE, HEAD, DELETE, etc) if they are not used.  Can also do this in the web.xml with security constraints,
15) add to the web.xml of the Kab CLI app:
user-data-constraint transport-guarantee CONFIDENTIAL transport-guarantee user-data-constraint
16) add an ibm-web-ext.xmi file to the app's WAR file with the following line: enable-directory-browsing value="false"

**Comment by davco01a** [comment]
Bruce and I will collaborate on this effort

**Comment by jtmulvey** [comment]
OK.  All this is in preparation for the coming Penetration test that will be done on this in the next month or so as part of SPbD.

**Comment by davco01a** [comment]
Hardening guide is here:

https://ibm.ent.box.com/s/blluvgl8pl8hmaiapk68byalavew64ip

**Comment by marikaj123** [comment]
Is it targeted for the Nov or Dec Kabanero release?

**Comment by davco01a** [comment]
re: `3) ensure the featureManager list only includes the web container (servlet feature)`

if we do this the security functionality won't work

**Comment by davco01a** [comment]
`5) use feature transportSecurity-1.0 instead of ssl-1.0`

we don't specify either one, get this under the umbrella of app-security

**Comment by davco01a** [comment]
@jtmulvey Please clarify second part of `9) and config dyn. updates config updateTrigger="mbean" in server.xml`

**Comment by davco01a** [comment]
14) Last make sure the servlet has all HTTP methods covered and return 403 (forbidden) (TRACE, HEAD, DELETE, etc) if they are not used. Can also do this in the web.xml with security constraints,

Already protected bc it's a JAX-RS app, already only allows the appropriate method call type due to JAX-RS annotations on the endpoints

**Comment by davco01a** [comment]
15) add to the web.xml of the Kab CLI app:
user-data-constraint transport-guarantee CONFIDENTIAL transport-guarantee user-data-constraint

N/A bc http has been disabled

**Comment by davco01a** [comment]
The updated server.xml:
```
<server description="Sample Liberty server">

	<featureManager>
        <feature>appSecurity-2.0</feature> 
        <feature>microProfile-2.0</feature>
    </featureManager>
  <!--  <featureManager>
        <feature>jaxrs-2.1</feature>
        <feature>mpConfig-1.3</feature>
        <feature>mpJwt-1.1</feature>
        <feature>json-1.0</feature>
  </featureManager>
  -->
  <httpEndpoint httpPort="-1" httpsPort="9443" id="defaultHttpEndpoint" host="*" />
  
  <webAppSecurity ssoRequiresSSL="true" httpOnlyCookies="true" /> 
  
  <httpSession cookieHttpOnly="true" allowOverflow="false" maxInMemorySessionCount="1000" alwaysEncodeUrl="true" cookieSecure="true"  />
  
  <applicationMonitor updateTrigger="mbean" dropinsEnabled="false" />
  
  <httpDispatcher enableWelcomePage="false" />
  
  <httpOptions removeServerHeader="true" />
  
  <webContainer disableXPoweredBy="true" />
  
      
   <!-- The issuer specified here must match the issuer configured in the jwtBuilder -->
    <mpJwt id="kabmpjwt" issuer="${jwt.issuer}" keyName="default" signatureAlgorithm="HS256" 
        sharedKey="${AESEncryptionKey}"/> 

    <!-- NOTE: This id cannot be changed since it's hard coded to be used in the runtime code -->
    <jwtBuilder expiresInSeconds="86400" id="kabsecbuilder" issuer="${jwt.issuer}" 
        keyStoreRef="defaultKeyStore" keyAlias="default" signatureAlgorithm="HS256" 
        sharedKey="${AESEncryptionKey}"/>
    
    
    <!--
    <keyStore id="defaultKeyStore" password="keyspass"/>
    -->
    <sslDefault sslRef="kabSSLConfig"/>
    <ssl id="kabSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="validationKeystore"/>
    <keyStore id="defaultKeyStore" />
    <keyStore id="validationKeystore" location="${server.config.dir}/resources/security/cacerts" type="jks" password="changeit"/>
    
    <!-- this will be the issuer of the jwts -->
    <variable name="jwt.issuer" defaultValue="https://kabasec.com" />
    
    <!-- this will be the default base url for github api calls -->
    <variable defaultValue="https://api.github.com" name="github.api.url" />


  <!-- Automatically expand WAR files and EAR files -->
  <applicationManager autoExpand="true"/>

  <applicationMonitor pollingRate="1000ms"/>
  
  

</server>
```

**Comment by davco01a** [comment]
cannot access the cli service from POSTMAN when this is coded in jvm.options:

`-Dcom.ibm.jsse2.sp800-131=strict`

**Comment by davco01a** [comment]
https://github.com/kabanero-io/kabanero-command-line-services/pull/72

**Comment by jtmulvey** [comment]
> @jtmulvey Please clarify second part of `9) and config dyn. updates config updateTrigger="mbean" in server.xml`

@davc01a See this article on the config server.xml element.  Add this element and specify updateTrigger=mbean.

**Comment by davco01a** [comment]
@jtmulvey Which article?

I cannot get to the hardening guide at:  

https://ibm.box.com/s/blluvgl8pl8hmaiapk68byalavew64ip  or 

https://ibm.ent.box.com/s/blluvgl8pl8hmaiapk68byalavew64ip

**Comment by davco01a** [comment]
added:

`<config updateTrigger="mbean"/>`

**Comment by davco01a** [comment]
cannot access the cli service from POSTMAN when this is coded in jvm.options:

-Dcom.ibm.jsse2.sp800-131=strict

All the other settings are in place

**Comment by davco01a** [comment]
@brutif still need to encrypt `keyspass` in keystore.xml file

**Comment by brutif** [comment]
@davco01a since the container is creating the keystore file on startup, I think we can just remove the password attribute from liberty/config/keystore.xml and remove the commented out <keystore...> element in server.xml.  Can you try this in your env and confirm it works?

**Comment by brutif** [comment]
@jtmulvey we notice keystore.xml is generated at docker build time by configure.sh, which is part of built  the base liberty docker image. 
```
sh-4.2$ cat ./configDropins/defaults/keystore.xml
<server description="Default Server">
    <keyStore id="defaultKeyStore" password="NIMvUeTsLnICqZqOL41Em8mhg+jPq6DcRWBLH13MBzg=" />
</server>sh-4.2$
```
The password is  randomly generated and unique to each container so stealing it doesn't accomplish anything. 
It -might- be possible to update https://github.com/OpenLiberty/ci.docker/blob/master/common/helpers/build/configure.sh to aesencrypt this password but I'm not sure it buys us anything.  Should we pursue that?

**Comment by davco01a** [comment]
@jtmulvey ^^^

**Comment by jtmulvey** [comment]
@brutif @davco01a Let's discuss this. Not sure I understand the rationale.  If someone can read the server.xml, they could use keytool with the password and obtain the private key used for the server's SSL. Once this is available, SSL is compromised to the targeted server.

**Comment by brutif** [comment]
@jtmulvey  since an unencrypted keystore password is the norm for all the liberty images, maybe the change should be made in the base images and then the cli server (and any others) would "inherit" it.
