### ISSUE TITLE
Put scan results in a location accessible to Jane

### ISSUE THREAD

**Issue by teddyjtorres** [kabanero-io/kabanero-security#36]
As a developer, Jane wants to access the scan results, preferably in an issue or pull request.

**Comment by jtmulvey** [comment]
Need to review this with @cajaygle

**Comment by teddyjtorres** [comment]
Changes delivered in https://github.com/kabanero-io/kabanero-pipelines/pull/186 for kabanero-pipelines and in https://github.com/kabanero-io/kabanero-security/pull/55 for kabanero-security.

**Comment by teddyjtorres** [comment]
The scan reports are now displayed in the tekton task output. A separate issue will need to be opened to make these integrated with the rest of the logging framework.
