### ISSUE TITLE
Container scanning follow-ups - PHASE 2

### ISSUE THREAD

**Issue by jtmulvey** [kabanero-io/kabanero-security#45]
There are several technical debt items that need resolution for the Kabanero container scanning support.

**Comment by teddyjtorres** [comment]
For issues #36 and #40.

**Comment by teddyjtorres** [comment]
Need to open issue for stopping the pipeline based on scan results.

**Comment by marikaj123** [comment]
According to Jim, the feature work is still on track to complete for Kabanero v.0.6.0

**Comment by teddyjtorres** [comment]
Reviewed issues #36, #39, and #40. Issue #40 is more likely to miss 0.6.0 since it would require additional refactoring to the pipelines, which were modified in https://github.com/kabanero-io/collections/commit/398fd29a2c6537266f538f73af76c793cc824064 in what appears to have been a kAppNav issue.

**Comment by marikaj123** [comment]
Need readme Documentation only

**Comment by marikaj123** [comment]
For Phase2, are there any gaps in Tekton that would require to be addressed in the coming phases?

**Comment by teddyjtorres** [comment]
The issues scheduled for this EPIC are now closed.
