### ISSUE TITLE
Container signing - PHASE 2

### ISSUE THREAD

**Issue by jtmulvey** [kabanero-io/kabanero-security#46]
Phase 1 for container signing offered a sample that could be placed in the Kabanero pipeline optionally. In Phase 2, we will provide this implementation as part of the Kabanero pipeline.

**Comment by marikaj123** [comment]
According to Jim, the feature work is still on track to complete for Kabanero v.0.6.0.

**Comment by toshiyamamoto** [comment]
the remaining image signing tasks have been identified as #51, #52, #53, and #54. This epic will be updated which one(s) will be in.

**Comment by marikaj123** [comment]
Needs Readme doc only.

**Comment by teddyjtorres** [comment]
Issue #51 was delivered. Toshi and I discussed and issues #52, #53, and #54 would need to move out of this EPIC into a new phase.

**Comment by teddyjtorres** [comment]
Opening "Container signing - PHASE 3"  for #52, #53, and #54.
