### ISSUE TITLE
Use Open Shift Certificate Manager for Open Liberty CA-signed server certs - Phase 2 (Design)

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-security#66]
Phase 2 to deliver the Certificate Manager Operator

We need to offer a way to configure the Open Liberty operator for Open Shift to get a new server's CA-signed server cert from the OKD/OCP certificate manager. This, like ICP, is based on the open source Jetstack implementation.

Need to deliver support in Open Liberty operator for OpenShift Cert ManagerNot estimated
Need to enable OpenShift Certificate Manager

**Comment by marikaj123** [comment]
Looking to complete the work in 0.9.0.

**Comment by jtmulvey** [comment]
After design meetings, we decided to go another path for signing Open Liberty server certs and not use Cert Manager (from Jetstack) as a default.
