### ISSUE TITLE
Use Open Shift Certificate Manager for Open Liberty CA-signed server certs - Phase 1 (sample script)

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-security#7]
We need to offer a way to configure the Open Liberty operator for Open Shift to get a new server's CA-signed server cert from the OKD/OCP certificate manager.  This, like ICP, is based on the open source Jetstack implementation.

**Comment by marikaj123** [comment]
According to Jim, the feature work is still on track to complete for Kabanero v.0.6.0.

**Comment by marikaj123** [comment]
Ut is helping with this issue

**Comment by marikaj123** [comment]
Needs Readme doc only.

**Comment by marikaj123** [comment]
May need a bolg issue

**Comment by utle** [comment]
We created a sample readme and script for customer to  install cert-manager and enable SSL for OpenLiberty instance.
https://github.com/kabanero-io/kabanero-security/tree/master/certmanager/samples/openliberty

**Comment by utle** [comment]
Completed - https://github.com/kabanero-io/kabanero-security/tree/master/certmanager/samples/openliberty

**Comment by utle** [comment]
Fixed by: jtmulvey/kabanero-security#3

**Comment by marikaj123** [comment]
Closing this Epic on behalf of Ut.
