### ISSUE TITLE
Update security/pipeline documentation for the image signing

### ISSUE THREAD

**Issue by toshiyamamoto** [kabanero-io/kabanero-security#74]
Since the image signing operator and the look aside signature store are in ICP4A only, either kabanero-security or kabanero-pipeline repo needs to have a documentation to describe how to manually enable the image signing. no need to mention how to configure for validation.

**Comment by marikaj123** [comment]
@toshiyamamoto and @kvijai82 - FOr any ID help you can connect with @jantley-ibm.

**Comment by jantley-ibm** [comment]
Per @stephenkinder this is OK to remain as a readme, no ID assistance needed. Removing documentation-id tag.

**Comment by marikaj123** [comment]
@toshiyamamoto - Are we using this issue to update the readme file?

**Comment by toshiyamamoto** [comment]
@marikaj123 yes. I'll create a separate doc issue ICP4A

**Comment by marikaj123** [comment]
@toshiyamamoto - Please close this issue and its Epic.  Thank you.
