### ISSUE TITLE
Provide a look aside signature server as a sample

### ISSUE THREAD

**Issue by toshiyamamoto** [kabanero-io/kabanero-security#76]
The target audience but not limited to is users who intend to enable the image signing and verification in a OpenShift cluster.
- server source code
- scripts for building an image of look aside signature server
- installation script
- documentation
    - usage instruction
    - default setting
    - configuration (secret usage/pvc, env. variable)
    - API

**Comment by marikaj123** [comment]
Sample code doc will be needed for readme.

documentation
    

- usage instruction
-     default setting
-     configuration (secret usage/pvc, env. variable)
-     API

**Comment by marikaj123** [comment]
According to Toshi, This work is to be done after Kabanero 0.9.0
